#The following iterative sequence is defined for the set of positive integers:
#
#n → n/2 (n is even)
#n → 3n + 1 (n is odd)
#
#Using the rule above and starting with 13, we generate the following sequence:
#
#13 → 40 → 20 → 10 → 5 → 16 → 8 → 4 → 2 → 1
#It can be seen that this sequence (starting at 13 and finishing at 1) contains 10 terms. Although it has not been proved yet (Collatz Problem), it is thought that all starting numbers finish at 1.
#
#Which starting number, under one million, produces the longest chain?
#
#NOTE: Once the chain starts the terms are allowed to go above one million.
import math as m

def b(x):
    if x%2 == 0:
        return x/2
    else:
        return 3*x+1


num=[]
n = 1000000



for i in range(-n,0):
    i = int(m.fabs(i))
    k = (i-1)/3
    if 2*i < n:   #generated by even
        num.append(0)
    elif (k%1 == 0) & (k%2 !=0):  # generated by odd
        num.append(0)
    else:
        num.append(i)

nums = num.copy()


for x in num:
    c = 1
    print(x, '..........................')
    if x != 0:
        z = x
        while (  z != 1):
            z = b(z)
            print(z)
            if z in num:
                num[  num.index(z)  ] = 0
            elif z <n:
                z =1










maximum = 0
max_value = 0
SEQUENCE_CACHE = dict()
for value in xrange(1, 1000000):
    status = value
    terms = 0
    while status > 1:
        try:
            terms += SEQUENCE_CACHE[status] - 1
            break
        except KeyError:
            pass
        
        if status % 2 == 0:
            #even
            status = status / 2
        else:
            # odd
            status = status * 3 + 1
        terms += 1

terms += 1
    SEQUENCE_CACHE[value] = terms
    
    if terms > maximum:
        max_value = value
        maximum = terms

print "value: %s   terms: %s" % (max_value, maximum)










